### ISSUE TITLE
White lines on artist pages.

### ISSUE THREAD

**Issue by Dronf3** [katelyynn/bleh#16]
Everytime I open any artist page on last.fm, white lines appear bellow the tags, under scrobble stats, under external links and under the shoutbox.

1. Go to any artist page on last.fm (eg. https://www.last.fm/music/Frank+Zappa)

**Expected behavior**
The page should load normally without the lines

![image](https://github.com/katelyynn/bleh/assets/114812232/815f815c-f2e0-4760-b428-4d0762a258f7)
![image](https://github.com/katelyynn/bleh/assets/114812232/ead3d9fd-b8fb-47ed-9053-6cbc3918b467)
![image](https://github.com/katelyynn/bleh/assets/114812232/5c6773db-1702-47bb-81b2-ee5df67d9542)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - bleh Version 20224.0618

**Comment by katelyynn** [comment]
likely last.fm ads being annoying again idk if this is a new change or not, never noticed due to adblocker

theyre making a lot of subtle stupid changes recently so who knows

**Comment by katelyynn** [comment]
fixed in latest but i recommend also using an adblocker anyway like ublock origin
![image](https://github.com/katelyynn/bleh/assets/46572320/5fe11d91-2852-4781-ba5a-8c94799635c9)

**Comment by Dronf3** [comment]
thanks. i am actually using ublock origin, so im not sure if that really is the issue.

**Comment by katelyynn** [comment]
> thanks. i am actually using ublock origin, so im not sure if that really is the issue.

well i wouldve fixed it if ublock origin hadnt been blocking them already :P i only saw them upon disabling it for last.fm

**Comment by Dronf3** [comment]
well that's weird..
