### ISSUE TITLE
Similar album names not visible

### ISSUE THREAD

**Issue by Orofil** [katelyynn/bleh#2]
Why are the titles set to `display: none` :(
![image](https://github.com/katelmao/lastfm-bleh/assets/49579906/3a93716d-0543-4889-8efb-90dff2781aca)

![image](https://github.com/katelmao/lastfm-bleh/assets/49579906/a717dc11-341c-4862-8cc1-e06881334f9d)

**Comment by katelyynn** [comment]
i know this is so so late i hadn't checked this for a while but this is fixed in the new release bleh2 if ur still somehow interested 😭

https://plexion.dev/bleh/fm/bleh2
