### ISSUE TITLE
artist capitalisation correction: VEXED

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#28]
**What type is this? (artist or album/track)**
Artist

**How should this be capitalised?**
VEXED

**Could you link the Last.fm page?**
[https://www.last.fm/music/Vexed](url)

**Do you have a source for this? (eg. Spotify)**
[https://open.spotify.com/artist/4ZwENj9UHL3ujCD3k7DfNH?si=nBMjw0fiQ5ej_0jlmV5O6g](url)

**Comment by ghost** [comment]
also question! would you prefer a separate post for _each_ artist or album/track or submit multiple on one post?

**Comment by katelyynn** [comment]
thank u!

for artists i'd prefer if an issue was made for each individual artist but if you have multiple albums/tracks under one artist u can compile them under one

it's just easier to group based on artist as that's how they're stored internally

**Comment by katelyynn** [comment]
as for the artist it does appear the vexed on spotify is the primary on last.fm so i'll merge

**Comment by katelyynn** [comment]
oh also u should be able to just paste links in and it will auto make them a clickable link
