### ISSUE TITLE
artist capitalisation correction: HEAVENSGATE

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#34]
**What type is this? (artist or album/track)**
Artist

**How should this be capitalised?**
HEAVENSGATE

**Could you link the Last.fm page?**
https://www.last.fm/music/HeavensGate

**Do you have a source for this? (eg. Spotify)**
https://open.spotify.com/artist/5xxpBuljNlb95kr6fcf6hj?si=60ba3cc2465a4c84

**Comment by katelyynn** [comment]
thanku

**Comment by ghost** [comment]
ur most welcome
