### ISSUE TITLE
fix: album pages for non-pro users

### ISSUE THREAD

**Issue by katelyynn** [katelyynn/bleh#4]
no clue how long this has been an issue, never had a report about it and never noticed since i have pro.. reported by @dronf3

strange

(on my main, pro)
![image](https://github.com/katelyynn/bleh/assets/46572320/fd253a2e-09cf-46b3-89c5-92220628af74)

(on my alt, no pro)
![image](https://github.com/katelyynn/bleh/assets/46572320/96c3fd20-be01-4cd7-a6b9-0ec5c8daab73)

**Comment by katelyynn** [comment]
i accidentally loaded a slightly different album tag on my main but its the same no matter which !!

**Comment by katelyynn** [comment]
fixed thankfully !! (lastfm is a mess and non-pro pages work differently due to them shoving an ad in the middle)

update: [cutensilly.org/bleh/fm](https://cutensilly.org/bleh/fm) (click the purple button!!)

**Comment by katelyynn** [comment]
i've jus extended this fix to artist, album, and track pages when using without pro, all seems to work now :3

**Comment by Dronf3** [comment]
thanks a lot for fixing this and sorry for not making this as an issue.

**Comment by katelyynn** [comment]
no worries !! glad i could help

**Comment by katelyynn** [comment]
turns out lastfm still loads ads even if u have pro it just hides them...

u can update again (if u want) it should hopefully mostly be fixed now
