### ISSUE TITLE
question or two!

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#43]
hi kate, quick questions for you!

1) is it okay if i plug your add-on on my last.fm profile? just want to show my support and spread knowledge cos i love it sfm💓

2) which brings me tooo: do you currently or plan to accept monetary donations aka something like ko-fi coffee tips? i've been wanting to ask that for awhile LOL 😭

**Comment by ghost** [comment]
also i want to add that i've been using last.fm since the beginning, gone through soooooo many accounts (like an insane amount cos my OCD gets the best of me) but the app is the only one of it's kind and it's just a vibe, you know.

bottom line:

the website downgrade was fucking insane and your add on is making it so much better and enjoyable to use again. and yeah dude, you just don't know how awesome i think you and this add on are, so ty LOL

**Comment by katelyynn** [comment]
this made me smile so thank u

1. go for it!! tha more the merrier
2. not at this moment but i will most likely open a ko-fi or something soonish so thank u if u do choose to <3

for now if u want to support along with tha plugging on profile u can star the repo here :3

**Comment by katelyynn** [comment]
on the website downgrade stuff yeah the 2015 redesign thing basically killed half of the site which is also what my sister project to bleh, https://github.com/katelyynn/bwaa will be when it releases (soonish)

bwaa will b an extension that brings lastfm back to its look around 2012 before tha redesign n stuffs

**Comment by ghost** [comment]
done and done! i really hope you open a ko-fi cos ofc <3

oooooh i can't wait for bwaa. i'll be switching back and forth i'm sure haha
