### ISSUE TITLE
2hollis - teenage soldier

### ISSUE THREAD

**Issue by all222s** [katelyynn/bleh#50]
**What type is this? (artist or album/track)**
track

**How should this be capitalised?**
"teenage soldier"

**Could you link the Last.fm page?**
https://www.last.fm/music/2hollis/_/TEENAGE+SOLDIER

**Do you have a source for this? (eg. Spotify)**
spotify / yt / sc / etc

**Comment by all222s** [comment]
also i just saw the thread LOL sorry if i should've put it there, it just took me to make a whole new issue when i clicked it from the configure page on lfm, wont happen again 😭

**Comment by katelyynn** [comment]
donesies
