### ISSUE TITLE
feature request: no top banner

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#51]
**Is your feature request related to a problem? Please describe.**
yeah it's a problem, for my eyes 👩🏾‍🦯

**Describe the solution you'd like**
just a simple option to disable the top banner

**Describe alternatives you've considered**
pretending it isn't there (yeah right)

**Additional context**
![image](https://github.com/user-attachments/assets/a0f6d1e0-d5a1-4c5a-bd71-5f74f7d65632)
look kate, look at the EYES

**Comment by ghost** [comment]
ALSO I LOVE THE SPOOKY THEME <3

**Comment by katelyynn** [comment]
thankuu i can do this rn actually

**Comment by katelyynn** [comment]
![image](https://github.com/user-attachments/assets/3c14411b-ceef-42e9-9eaa-b18c012c9dcc)
in latest !
