### ISSUE TITLE
Run-at document-body doesn't work in Firefox/ViolentMonkey

### ISSUE THREAD

**Issue by clr134** [katelyynn/bleh#53]
**Describe the bug**
Running with ViolentMonkey in Firefox, bleh fails to run, it looks for username/auth elements, but fails because they don't exist yet. Changing run-at to document-end fixes it, as does removing those two lines in favor of hardcoding (which is annoying as it has to be done every update):
```js
auth_link = document.querySelector('a.auth-link');
auth = auth_link.querySelector('img').getAttribute('alt');
```

Console log doesn't show up for me at this moment, did before, but it just confirms the above.

**To Reproduce**
1. Open https://www.last.fm/bleh
2. See 404

**Expected behavior**
bleh settings page

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox, ViolentMonkey
 - bleh Version: 2024.1007

**Additional context**
It's possible it works in TamperMonkey or others, untested.

**Comment by katelyynn** [comment]
i use tampermonkey personally so i can confirm it's always worked but if this doesn't affect performance i see no issue changing :3 thank u

**Comment by katelyynn** [comment]
also yeag i can most likely change those auth things to only run once as i assume lastfm reloads the page on new account anyway

auth_link is most likely redundant too

**Comment by clr134** [comment]
Thanks :3
