### ISSUE TITLE
artist capitalisation correction: iri

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#56]
**What type is this? (artist or album/track)**
artist

**How should this be capitalised?**
iri

**Could you link the Last.fm page?**
[...](https://www.last.fm/music/Iri)

**Do you have a source for this? (eg. Spotify)**
[...](https://open.spotify.com/artist/1mN9lPKzTRTOop4u7S1Uy9?si=_M0e-rRXSW-QxO4bRuDjNQ)

**Comment by katelyynn** [comment]
doneee

**Comment by ghost** [comment]
tysmmm <3
