### ISSUE TITLE
Bring back scrobbler / listener track on song pages

### ISSUE THREAD

**Issue by clr134** [katelyynn/bleh#59]
As someone who maintains a local music collection, I often adjust the tags I scrobble to match the most-used entry for a given track on Last.fm, this is vital for me, especially with Japanese music which often has multiple entries with differing artist credits and romanization.  Also it's nice to see I guess.

**Comment by katelyynn** [comment]
the huh? do u mean these, if so they are still visible and actually bigger than before
![image](https://github.com/user-attachments/assets/1bbf96ba-7591-42aa-b0b9-c9a03c897853)

i can always add additional display alternatives if theres a better place you feel they can be - for example next to this if that helps? :3 
![image](https://github.com/user-attachments/assets/42e5bc1e-121e-4a59-a906-1006ebb655b0)

**Comment by clr134** [comment]
Oh god, yeah, sorry. I didn't see them I even tried looking but I couldn't find them anywhere.

**Comment by katelyynn** [comment]
no worries!
