### ISSUE TITLE
special character artist names not appearing correctly

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#61]
**Describe the bug**
I'm not sure if this is occurring with other artists with special character names, but when I go to the artist page of say 中島美嘉 (Mika Nakashima), her name in top tracks is a fiesta.

**To Reproduce**
1. Go to ['...'](https://www.last.fm/music/%E4%B8%AD%E5%B3%B6%E7%BE%8E%E5%98%89)
2. Top tracks = ARTIST FIESTA %E4%B8%AD%E5%B3%B6%E7%BE%8E%E5%98%89

**Expected behavior**
中島美嘉 japanese characters

**Screenshots**
![image](https://github.com/user-attachments/assets/07a1389e-4e33-442f-9938-b26765a720b9)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - bleh Version [2024.1015.falter]

**Additional context**
... fiesta

**Comment by katelyynn** [comment]
ive been seeing this randomly but yeag BUT u posting htis made me realise i think i know why so i can try look in the morning or sum

most likely its reading the artist name from the url but those special (unicode) characters that arent plain english get changed to look like that bla bla nerd stuff

**Comment by katelyynn** [comment]
i love one-line fixes
