### ISSUE TITLE
Scrobbles Don't Appear on Album or Track Pages

### ISSUE THREAD

**Issue by UserNo84** [katelyynn/bleh#62]
Hi!

Well, the title says it all. Since (one of) the last update(s), the scrobbles won't be displayed anymore on any album or track page.
![screencapture-last-fm-music-Radiohead-Creep-2024-10-18-01_24_26](https://github.com/user-attachments/assets/4075b0d5-ad04-415f-a33e-5687b1036804)

**Comment by katelyynn** [comment]
thats cus the page isnt logged in as u can see, lastfm bug

**Comment by UserNo84** [comment]
I'm referring to global scrobbles, not my personal ones. Perhaps take a moment to actually look at the image attached before rushing to reply. Here's two more images, one with and one without your style. It's not a Last.fm bug, it's your style.

![Screenshot (72)](https://github.com/user-attachments/assets/b4649645-322a-4fff-b85c-46c65f17d995)
![Screenshot (73)](https://github.com/user-attachments/assets/c24d83c7-5a53-42d9-b37e-31bb9bee7f90)

Oh, and by the way, there are still no "followers" and "neighbors" sections.

![Screenshot (74)](https://github.com/user-attachments/assets/7b224d10-8b6d-41bf-b5f3-16bf2cf70dc3)

**Comment by katelyynn** [comment]
no like i said its cus ur still not logged in :p bleh isn't designed for being logged out yet cus that's so low priority

**Comment by katelyynn** [comment]
also i would hope u installed it correctly, follow the proper install instructions on the site if u only installed it with stylus

**Comment by UserNo84** [comment]
I'm just using the theme for Stylus now. I removed the Tampermonkey script because it’s broken and blocks half of Last.fm, including my own profile, labelling it as 'hateful'. Seems like you need your little echo chamber to get by.

As I said, the issue I mentioned began around two weeks ago, and it’s not related to whether I'm logged in or not since it's not caused by the Tampermonkey script.

**Comment by katelyynn** [comment]
ur clearly not reading what im saying, u didnt install it correctly (support is not offered if ur not using the extension, that is literlaly what bleh is), bla bla bla enjoy the rest of ur day

"blocks half of last.fm" says a lot more about who u associate with anyway (the block isnt even there anymore but still)
