### ISSUE TITLE
artist capitalisation correction: ROSÉ

### ISSUE THREAD

**Issue by ghost** [katelyynn/bleh#67]
**What type is this? (artist or album/track)**
artist

**How should this be capitalised?**
ROSÉ

**Could you link the Last.fm page?**
[...](https://www.last.fm/music/Ros%C3%A9)

**Do you have a source for this? (eg. Spotify)**
[...](https://open.spotify.com/artist/3eVa5w3URK5duf6eyVDbu9?si=j2uyPCh4TWSOmRi9fxHnbg)

i swear this is my last one 😩 (that may be a lie) and ty <3

**Comment by katelyynn** [comment]
ofc
