### ISSUE TITLE
bulk edit extension causes album and artist title conflict

### ISSUE THREAD

**Issue by peudepeu** [katelyynn/bleh#70]
**Describe the bug**
When viewing my profile, at the Recent Tracks, if the artist name is long, the album title will overlap with the name.

**To Reproduce**
1. Go to any user profile that recently listened to an artist with a long name
2. See error

**Expected behavior**
I expected the title of the album to be further away from the name of the artist

**Screenshots**
![image](https://github.com/user-attachments/assets/88d8b9dd-9ac6-47fe-82b5-d5eb714e5da3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave
 - bleh Version: 2024.1029

**Comment by katelyynn** [comment]
i assume ur using the last.fm bulk edit extension? still need to add compatibility for that, ill try move it to the space on the right or something

**Comment by peudepeu** [comment]
Ah yes, I do use Bulk edit. Deactivated it and it looks fine. Guess I'll just activate it when I need it. Thanks for the great work you do with bleh!

**Comment by katelyynn** [comment]
thank u!!

i plan on most likely adding a toggle in bleh to hide that album text if u use bulk edit - still unsure if i should have it on or off by default rn thou (the position will be fixed too obviously)

hovering over tracks shows the album title in bleh so i feel its unnecessary by default personally

**Comment by katelyynn** [comment]
that should do it once updated i believe! (hopefully)

new option (off by default) will control whether the album title appears
![image](https://github.com/user-attachments/assets/f021c9e2-ff08-4741-a0b8-4ec8f6e6d0c3)

ive tested all 4 combos of those 2 toggles and they seem to look okay (i would still recomended keeping stacked chartlist info on thou as it looks best imo at least)
