### ISSUE TITLE
LIKE A KID

### ISSUE THREAD

**Issue by peudepeu** [katelyynn/bleh#72]
**What type is this? (artist or album/track)**
Artist

**How should this be capitalised?**
LIKE A KID

**Could you link the Last.fm page?**
[...](https://www.last.fm/music/Like+a+Kid)

**Do you have a source for this? (eg. Spotify)**
A source helps me verify this capitalisation is the most popular and should be applied. Enter one here.
https://open.spotify.com/artist/2W0JEVzX3Ukiwd8IhrikzN?si=rzwLPpZSRBOHNdeaHVvsUA
https://musicbrainz.org/artist/0f55abf6-f7c2-4624-a95f-aaa6b0d86e9b

**Comment by katelyynn** [comment]
doneee
