### ISSUE TITLE
artist/album/track capitalisation correction thread

### ISSUE THREAD

**Issue by katelyynn** [katelyynn/bleh#9]
# [TO SUBMIT A CORRECTION CLICK HERE](https://github.com/katelyynn/bleh/issues/new/choose)

you can submit corrections for either an artist or an album/track (albums/tracks are not differentiated)

in the case there are multiple artists using a page, the most popular artist will be used to determine the capitalisation. this is based on an artist's top tracks compared to eg. a spotify page. this can be seen most obviously in the case of [funeral](https://www.last.fm/music/Funeral), where the top tracks that r most popular r attributed to the [lowercase funeral](https://open.spotify.com/artist/3f0Mhz0oXmnsnehuEGTrfd?si=LpV8APuLRmClhZ5A98JPQQ).

---

info on capitalisations can be found in [the wiki](https://github.com/katelyynn/bleh/wiki/Capitalisation-corrections)

**Comment by ghost** [comment]
[https://www.last.fm/music/Thrown](url)
Thrown -> thrown
(also HI, i love bleh sfm <3 )

**Comment by katelyynn** [comment]
> [https://www.last.fm/music/Thrown](url) Thrown -> thrown (also HI, i love bleh sfm <3 )

tracks match [the page](https://open.spotify.com/artist/5eBCPtU2iPbzuMRre9BePt?si=KbKw8eYESRSSa0ZNkX3uwg) and they are the most popular on the last.fm page by _a lot_ so i'll get this in the next update thank u (thank u again btw !!)

**Comment by katelyynn** [comment]
ive decided to lock this thread and move to the issue template to b more organised :3
