### ISSUE TITLE
Seeing average scrobbles per day

### ISSUE THREAD

**Issue by peudepeu** [katelyynn/bleh#91]
Hi!

In the original Lastfm view of a user profile, when hovering over the total scrobble count you would see "That's an average of 47 scrobbles per day!". In bleh, it simply says "Scrobbles". Could the original information become available in bleh?

**Comment by katelyynn** [comment]
honestly i can't believe i forgot this i can get it fixed when im back

**Comment by katelyynn** [comment]
will be in next release
