### ISSUE TITLE
Year of comments in shoutbox

### ISSUE THREAD

**Issue by peudepeu** [katelyynn/bleh#96]
In shoutboxes on user profiles and artist profiles, the shouts have a time stamp from when they were posted.
In original Lastfm, they are formated with date-month-time, as in bleh.
The difference is, when hovering over the time stamp in original, it also shows weekday-date-month-year-time.
In bleh, it instead of showing the year shows "copy link".
Since the site is about 20 years old, it can sometimes be useful to see what year the last shout was posted.
Could you bring back the year when hovering, or maybe even bring back the year without the need to hover?

**Comment by katelyynn** [comment]
the year does show for older shouts by default in last.fm :3 
![image](https://github.com/user-attachments/assets/a5c94cbf-c4b6-45dd-9188-4f06d5e6b660)

but yes i have been planning to remove that copy link stuff i changed it ovr a year ago and its been bugging me too that i cant see the full date 😭
