### ISSUE TITLE
clicking toggles in auto edit modal does nothing (clicking the label does)

### ISSUE THREAD

**Issue by jabreen** [katelyynn/bleh#97]
**Describe the bug**

attempting to bulk edit scrobbles and clicking the tickboxes to change all scrobbles/make it an automatic edit does not work

**To Reproduce**
- select any song in your library
- click Bulk edit scrobbles
- click bulk edit switch or automatic edit switch
- switch does not activate

**Expected behavior**
switches activate

**Screenshots**
![firefox_13GkDHoGHy](https://github.com/user-attachments/assets/3b36ab33-653d-4adc-abca-c9147d5d400b)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser: firefox
 - bleh Version: 2024.1113.yoshimi

**Additional context**

**Comment by katelyynn** [comment]
ive not tested hitting save but it does seem to work u probably got tricked by clicking the toggle itself not working (but clicking the label does) - i will fix that thou dont worry lmao
![image](https://github.com/user-attachments/assets/76d9579a-6c13-4bce-87f0-fef067ab8933)

tha next ver will have a lil fixed up design for bulk editing in bleh too cus i thought i may as well while i was here :3 thank u 4 reporting thou as usual

**Comment by katelyynn** [comment]
i do wonder why that bug is happening actually tho clicking the toggle should work just fine

**Comment by katelyynn** [comment]
will b fixed in next release :3

**Comment by jabreen** [comment]
works on my end w/ 1120.iroha!!
